# Generated by Django 5.2.6 on 2025-09-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('regiao', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
