# Generated by Django 5.2.6 on 2025-09-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pontoturistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='app.estado'),
        ),
    ]
